### ISSUE TITLE
Can't install/blue screen

### ISSUE THREAD

**Issue by Dharengo** [Dazzozo/humblehax#2]
Hello,

So I'm trying to use the latest browserhax in order to exploit citizens of earth, because I do not like how menuhax messes up my home menu. I'm on a european old3DSXL, FW 11.0.
However, when I try to run the salt sploit installer, the screen just spazzes out a little bit, ending on a dark blue screen, and then nothing.

Am I doing something wrong?

**Comment by asialsky** [comment]
Same issue here. FW 11.0 o3DS w/ latest update. (Menuhax 3.0, hblauncher 1.1.1)
*hax cycles through colors, and stops on blue.

I've tried deleting my saves, saving only to slot 1, then 3. No dice.

EDIT: I should also mention that the current game version shows as 1.2.0 at the title screen. We may need another mmap!

**Comment by wouterv1** [comment]
Same here :/

**Comment by dazjo** [comment]
Looks like this is happening only on old 3DS?

FWIW, v2 = 1.2.0, v1 = 1.1.0.

**Comment by wouterv1** [comment]
I think so..

**Comment by wouterv1** [comment]
Can you fix it?

**Comment by asialsky** [comment]
Any progress on making this work for o3DS?

**Comment by noegodinho** [comment]
I don't know if this has gotten any progress, but I'm having problems as well.
I have an Old3DS with 11.0.0.33 EUR and when I try to patch CoE with the new v2.3, I have a blue screen as well.
Also, awkwardly enough, I have a green screen with v2.0 to v2.2 and cannot patch either way (I'm using supermysterychunkhax) and with v1.x is impossible to patch since I have 1.2.0 from the store.

**Comment by dazjo** [comment]
Should be *finally* fixed with v3 and *hax 2.8 due to new takeover method
